### ISSUE TITLE
runtime error when calling lua function from C++, passing a const char*

### ISSUE THREAD

**Issue by TrianglesPCT** [rpavlik/luabind#29]
Trying to convert from luabind(the boost version) to this one, getting error at startup.

const char\* path =  "..\code\script\?.lua;"
luabind::call_function<void>(_State, "set_path",path);

It seems to be trying to find the class_id for "const char_", not finding anything, and then reporting that const char_ is not a registered class.

" Trying to use unregistered class: char const *"

**Comment by decimad** [comment]
Please let me know if this is resolved or if you've given up on it.
